// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AiDiagnosis = {
    summary: string;
    evidenceIds: Array<string>;
    codeReferences: Array<CodeReference>;
    rank: number;
    evidenceStrength: number;
};

export type AiSummaryPart = {
    text: string;
    referenceId?: null | string;
};

export type AiSummaryReference = {
    id: string;
    label: string;
    kind: string;
    href: string;
};

export type AiSynthesis = {
    status: string;
    summary: null | string;
    possibleContributors: Array<string>;
    unknowns: Array<string>;
    recommendedChecks: Array<string>;
    evidenceHash: null | string;
    diagnoses: null | Array<AiDiagnosis>;
    summaryParts: null | Array<AiSummaryPart>;
    summaryReferences: null | Array<AiSummaryReference>;
};

export type CausalEvent = {
    id: string;
    category: string;
    label: null | string;
    occurredAt: string;
    summary: string;
    source: string;
    evidenceId: string;
    actor: null | string;
    url: null | string;
    objectType: null | string;
    objectId: null | string;
    codeReferences: Array<CodeReference>;
};

export type CodeReference = {
    id: string;
    projectId: string;
    commitSha: string;
    path: string;
    startLine: number;
    endLine: number;
    url: string;
    excerpt: string;
};

export type DemoAvailability = {
    enabled: boolean;
    incidentId: string;
    incidentUrl: string;
};

export type DemoReset = {
    incidentId: string;
    incidentUrl: string;
    version: number;
};

export type EvidenceFinding = {
    id: string;
    source: string;
    occurredAt: string;
    endedAt: null | string;
    category: string;
    severity: string;
    summary: string;
    excerpt: null | string;
    url: null | string;
    confidence: number;
    provenance: JsonObject;
    actor: null | string;
    objectType: null | string;
    objectId: null | string;
    codeReferences: null | Array<CodeReference>;
};

export type FingerprintStage = 'provisional' | 'final';

export type IncidentPending = {
    id: string;
    pagerDutyIncidentId: string;
    serviceId: string;
    profileId: string;
    title: string;
    urgency: string;
    state: IncidentState;
    status: string;
    triggeredAt: string;
    updatedAt: string;
    version: number;
};

export type IncidentState = 'triggered' | 'acknowledged' | 'escalated' | 'reassigned' | 'resolved' | 'unknown';

export type IncidentStatus = {
    id: string;
    status: string;
    state: IncidentState;
    version: number;
    updatedAt: string;
    isFrozen: boolean;
};

export type IncidentStatusChanged = {
    incidentId: string;
    status: string;
    version: number;
};

export type IncidentUpdated = {
    incidentId: string;
    version: number;
    changedSections: Array<string>;
};

export type InvestigationReport = {
    id: string;
    pagerDutyIncidentId: string;
    serviceId: string;
    profileId: string;
    profileRevision: string;
    title: string;
    urgency: string;
    state: IncidentState;
    status: string;
    triggeredAt: string;
    updatedAt: string;
    version: number;
    deterministicSummary: string;
    ai: AiSynthesis;
    timeline: Array<TimelineEvent>;
    evidence: Array<EvidenceFinding>;
    sources: Array<SourceReport>;
    links: Array<SourceLink>;
    causalEvents: null | Array<CausalEvent>;
    problem: null | ProblemContext;
};

export type JsonObject = {
    [key: string]: unknown;
};

export type PageOfEvidenceFinding = {
    total: number;
    items: Array<EvidenceFinding>;
};

export type PageOfTimelineEvent = {
    total: number;
    items: Array<TimelineEvent>;
};

export type PossibleProblemMatch = {
    problemKey: string;
    matchType: string;
    score: number;
    matchedFeatures: Array<string>;
    lastSeen: string;
};

export type ProblemContext = {
    availability: string;
    algorithmVersion: string;
    stage: FingerprintStage;
    problemKey: null | string;
    problemGroupId: null | string;
    lifecycleState: null | ProblemLifecycleState;
    matchType: null | string;
    matchScore: null | number;
    matchedFeatures: Array<string>;
    occurrenceCount: number;
    firstSeen: null | string;
    lastSeen: null | string;
    recentOccurrences: Array<ProblemOccurrence>;
    possibleMatches: Array<PossibleProblemMatch>;
    completeness: number;
    diagnostic: null | string;
};

export type ProblemLifecycleState = 'new' | 'ongoing' | 'resolved' | 'regressed' | 'escalating';

export type ProblemOccurrence = {
    incidentId: string;
    pagerDutyIncidentId: string;
    state: IncidentState;
    occurredAt: string;
    updatedAt: string;
    reportUrl: null | string;
};

export type SourceHealth = 'pending' | 'complete' | 'partial' | 'unavailable' | 'excluded';

export type SourceLink = {
    label: string;
    url: string;
};

export type SourceReport = {
    source: string;
    health: SourceHealth;
    findingCount: number;
    durationMilliseconds: number;
    diagnostic: null | string;
    links: Array<SourceLink>;
};

export type TimelineEvent = {
    occurredAt: string;
    source: string;
    kind: string;
    summary: string;
    severity: string;
    url: null | string;
    actor: null | string;
    objectType: null | string;
    objectId: null | string;
};

export type GetHealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type GetHealthLiveResponses = {
    200: unknown;
};

export type GetHealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type GetHealthReadyResponses = {
    200: unknown;
};

export type GetDemoAvailabilityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo';
};

export type GetDemoAvailabilityResponses = {
    200: DemoAvailability;
};

export type GetDemoAvailabilityResponse = GetDemoAvailabilityResponses[keyof GetDemoAvailabilityResponses];

export type ResetDemoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo/reset';
};

export type ResetDemoResponses = {
    200: DemoReset;
};

export type ResetDemoResponse = ResetDemoResponses[keyof ResetDemoResponses];

export type GetIncidentReportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/incidents/{id}';
};

export type GetIncidentReportErrors = {
    404: unknown;
};

export type GetIncidentReportResponses = {
    200: InvestigationReport;
    202: IncidentPending;
};

export type GetIncidentReportResponse = GetIncidentReportResponses[keyof GetIncidentReportResponses];

export type GetIncidentStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/incidents/{id}/status';
};

export type GetIncidentStatusErrors = {
    404: unknown;
};

export type GetIncidentStatusResponses = {
    200: IncidentStatus;
};

export type GetIncidentStatusResponse = GetIncidentStatusResponses[keyof GetIncidentStatusResponses];

export type GetIncidentTimelineData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/incidents/{id}/timeline';
};

export type GetIncidentTimelineErrors = {
    404: unknown;
};

export type GetIncidentTimelineResponses = {
    200: PageOfTimelineEvent;
};

export type GetIncidentTimelineResponse = GetIncidentTimelineResponses[keyof GetIncidentTimelineResponses];

export type GetIncidentEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/incidents/{id}/evidence';
};

export type GetIncidentEvidenceErrors = {
    404: unknown;
};

export type GetIncidentEvidenceResponses = {
    200: PageOfEvidenceFinding;
};

export type GetIncidentEvidenceResponse = GetIncidentEvidenceResponses[keyof GetIncidentEvidenceResponses];
