// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AiDiagnosis = {
    summary: string;
    crumbIds: Array<string>;
    codeReferences: Array<CodeReference>;
    rank: number;
    crumbStrength: number;
};

export type AiSummaryPart = {
    text: string;
    referenceId?: null | string;
};

export type AiSummaryReference = {
    id: string;
    label: string;
    kind: string;
    href: string;
};

export type AiSynthesis = {
    status: string;
    summary: null | string;
    possibleContributors: Array<string>;
    unknowns: Array<string>;
    recommendedChecks: Array<string>;
    crumbHash: null | string;
    diagnoses: null | Array<AiDiagnosis>;
    summaryParts: null | Array<AiSummaryPart>;
    summaryReferences: null | Array<AiSummaryReference>;
};

export type AiSynthesisProgressState = 'pending' | 'running' | 'complete' | 'unavailable' | 'skipped';

export type AppendCrumbsRequest = {
    batchId: string;
    crumbs: Array<SubmittedCrumb>;
};

export type AppendCrumbsResponse = {
    accepted: number;
    duplicates: number;
    inputVersion: number;
    projectedInputVersion: number;
    rebuildQueued: boolean;
    duplicateBatch?: boolean;
};

export type CaseEarlyCrumb = {
    id: string;
    source: string;
    occurredAt: string;
    severity: string;
    summary: string;
    confidence: number;
};

export type CaseFile = {
    caseId: string;
    pagerDutyIncidentId: null | string;
    serviceId: string;
    recipeId: string;
    recipeRevision: string;
    title: string;
    urgency: string;
    pagerDutyState: PagerDutyIncidentState;
    status: string;
    openedAt: string;
    updatedAt: string;
    caseFileVersion: number;
    deterministicSummary: string;
    ai: AiSynthesis;
    trail: Array<TrailEntry>;
    crumbs: Array<Crumb>;
    crumbSources: Array<CrumbSourceStatus>;
    links: Array<SourceLink>;
    causalMarkers: null | Array<CausalMarker>;
    pattern: null | PatternContext;
    origin?: CaseOrigin;
    inputVersion?: number;
    projectedInputVersion?: number;
    createdBy?: null | string;
};

export type CaseInput = {
    id: string;
    sequence: number;
    inputVersion: number;
    clientCrumbId: string;
    producerPrincipal: string;
    receivedAt: string;
    occurredAt: string;
    kind: SubmittedCrumbKind;
    category: string;
    severity: string;
    summary: string;
    excerpt: null | string;
    declaredSource: null | string;
    sourceReference: null | string;
    url: null | string;
    actor: null | string;
    objectType: null | string;
    objectId: null | string;
    attributes: {
        [key: string]: unknown;
    };
    trustLevel: string;
    supersedesCrumbId: null | string;
    supersededByCrumbId: null | string;
    retractedAt: null | string;
    retractedInputVersion: null | number;
    active: boolean;
    projectedInInputVersion: null | number;
};

export type CaseOrigin = {
    kind: CaseOriginKind;
    externalId: null | string;
};

export type CaseOriginKind = 'pagerDuty' | 'agent' | 'manual';

export type CasePending = {
    caseId: string;
    pagerDutyIncidentId: null | string;
    serviceId: string;
    recipeId: string;
    title: string;
    urgency: string;
    pagerDutyState: PagerDutyIncidentState;
    status: string;
    openedAt: string;
    updatedAt: string;
    caseFileVersion: number;
    origin?: CaseOrigin;
    inputVersion?: number;
    projectedInputVersion?: number;
    createdBy?: null | string;
};

export type CaseProgressPhase = 'collecting' | 'synthesizing' | 'finalizing' | 'completed';

export type CaseProgressProjection = {
    caseId: string;
    attemptId: string;
    revision: number;
    baseCaseFileVersion: number;
    startedAt: string;
    updatedAt: string;
    elapsedDurationMilliseconds: number;
    phase: CaseProgressPhase;
    currentPass: number;
    currentLookbackMinutes: number;
    deterministicCaseFileUsable: boolean;
    onlyAiSynthesisRemaining: boolean;
    aiSynthesisState: AiSynthesisProgressState;
    crumbSources: Array<CrumbSourceProgress>;
    earlyCrumbs: Array<CaseEarlyCrumb>;
};

export type CaseStatus = {
    caseId: string;
    status: string;
    pagerDutyState: PagerDutyIncidentState;
    caseFileVersion: number;
    updatedAt: string;
    isFrozen: boolean;
    inputVersion?: number;
    projectedInputVersion?: number;
    progress?: null | CaseProgressProjection;
};

export type CaseStatusChanged = {
    caseId: string;
    status: string;
    caseFileVersion: number;
    inputVersion?: number;
    projectedInputVersion?: number;
};

export type CaseTriggerResult = {
    caseId: string;
    caseUrl: string;
    duplicate: boolean;
};

export type CaseUpdated = {
    caseId: string;
    caseFileVersion: number;
    changedSections: Array<string>;
    inputVersion?: number;
    projectedInputVersion?: number;
    status?: null | string;
};

export type CausalMarker = {
    id: string;
    category: string;
    label: null | string;
    occurredAt: string;
    summary: string;
    source: string;
    crumbId: string;
    actor: null | string;
    url: null | string;
    objectType: null | string;
    objectId: null | string;
    codeReferences: Array<CodeReference>;
};

export type CodeReference = {
    id: string;
    projectId: string;
    commitSha: string;
    path: string;
    startLine: number;
    endLine: number;
    url: string;
    excerpt: string;
};

export type CreateCaseRequest = {
    recipeId: string;
    title: string;
    serviceId: string;
    urgency: string;
    referenceTime: string;
    labels?: null | {
        [key: string]: string;
    };
    idempotencyKey?: null | string;
};

export type CreateCaseResponse = {
    caseId: string;
    origin: CaseOriginKind;
    inputVersion: number;
    projectedInputVersion: number;
    caseFileVersion: number;
    status: string;
    caseUrl: string;
    duplicate?: boolean;
};

export type Crumb = {
    id: string;
    source: string;
    occurredAt: string;
    endedAt: null | string;
    category: string;
    severity: string;
    summary: string;
    excerpt: null | string;
    url: null | string;
    confidence: number;
    provenance: JsonObject;
    actor: null | string;
    objectType: null | string;
    objectId: null | string;
    codeReferences: null | Array<CodeReference>;
};

export type CrumbSourceHealth = 'pending' | 'complete' | 'partial' | 'unavailable' | 'excluded';

export type CrumbSourceProgress = {
    source: string;
    requestState: CrumbSourceProgressState;
    health: CrumbSourceHealth;
    pass: number;
    lookbackMinutes: number;
    durationMilliseconds: number;
    crumbCount: number;
    diagnostic: null | string;
    startedAt: null | string;
    updatedAt: string;
};

export type CrumbSourceProgressState = 'pending' | 'querying' | 'received' | 'timedOut' | 'failed' | 'excluded';

export type CrumbSourceRequestState = 'requested' | 'received' | 'errored';

export type CrumbSourceStatus = {
    source: string;
    health: CrumbSourceHealth;
    crumbCount: number;
    durationMilliseconds: number;
    diagnostic: null | string;
    links: Array<SourceLink>;
    requestState: CrumbSourceRequestState;
};

export type DemoAvailability = {
    enabled: boolean;
    caseId: string;
    caseUrl: string;
};

export type DemoReset = {
    caseId: string;
    caseUrl: string;
    caseFileVersion: number;
};

export type JsonObject = {
    [key: string]: unknown;
};

export type ObservedServiceCatalogItem = {
    recipeId: string;
    pagerDutyServiceId: string;
};

export type OperationsCatalog = {
    teams: Array<TeamCatalogItem>;
};

export type PageOfCaseInput = {
    total: number;
    items: Array<CaseInput>;
};

export type PageOfCrumb = {
    total: number;
    items: Array<Crumb>;
};

export type PageOfTrailEntry = {
    total: number;
    items: Array<TrailEntry>;
};

export type PagerDutyIncidentState = 'triggered' | 'acknowledged' | 'escalated' | 'reassigned' | 'resolved' | 'unknown';

export type PatternContext = {
    availability: string;
    algorithmVersion: string;
    stage: SignatureStage;
    patternKey: null | string;
    patternId: null | string;
    lifecycleState: null | PatternLifecycleState;
    matchType: null | string;
    matchScore: null | number;
    matchedFeatures: Array<string>;
    occurrenceCount: number;
    firstSeen: null | string;
    lastSeen: null | string;
    recentOccurrences: Array<PatternOccurrence>;
    possibleMatches: Array<PossiblePatternMatch>;
    completeness: number;
    diagnostic: null | string;
};

export type PatternLifecycleState = 'new' | 'ongoing' | 'resolved' | 'regressed' | 'escalating';

export type PatternOccurrence = {
    caseId: string;
    pagerDutyIncidentId: null | string;
    pagerDutyState: PagerDutyIncidentState;
    occurredAt: string;
    updatedAt: string;
    caseUrl: null | string;
};

export type PossiblePatternMatch = {
    patternKey: string;
    matchType: string;
    score: number;
    matchedFeatures: Array<string>;
    lastSeen: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type RebuildCaseFileResponse = {
    caseId: string;
    targetInputVersion: number;
    rebuildQueued: boolean;
};

export type RecentCase = {
    caseId: string;
    origin: CaseOriginKind;
    recipeId: string;
    serviceId: string;
    title: string;
    status: string;
    inputVersion: number;
    projectedInputVersion: number;
    caseFileVersion: number;
    createdBy: null | string;
    updatedAt: string;
    caseUrl: string;
};

export type RecentCases = {
    total: number;
    cases: Array<RecentCase>;
};

export type RecentPagerDutyIncident = {
    id: string;
    incidentNumber: number;
    title: string;
    status: string;
    urgency: string;
    createdAt: string;
    lastStatusChangeAt: string;
    serviceId: string;
    serviceName: string;
    assignees: Array<string>;
    htmlUrl: null | string;
};

export type RecentPagerDutyIncidents = {
    since: string;
    until: string;
    hasMore: boolean;
    incidents: Array<RecentPagerDutyIncident>;
};

export type RefreshCaseSourcesResponse = {
    caseId: string;
    targetInputVersion: number;
    refreshQueued: boolean;
};

export type ServiceCollectionCatalogItem = {
    id: string;
    services: Array<ObservedServiceCatalogItem>;
};

export type SignatureStage = 'provisional' | 'final';

export type SourceLink = {
    label: string;
    url: string;
};

export type SubmittedCrumb = {
    clientCrumbId: string;
    kind: SubmittedCrumbKind;
    occurredAt: string;
    category: string;
    severity: string;
    summary: string;
    excerpt?: null | string;
    declaredSource?: null | string;
    sourceReference?: null | string;
    url?: null | string;
    actor?: null | string;
    objectType?: null | string;
    objectId?: null | string;
    attributes?: null | {
        [key: string]: unknown;
    };
    supersedesClientCrumbId?: null | string;
};

export type SubmittedCrumbKind = 'event' | 'crumb' | 'note';

export type TeamCatalogItem = {
    id: string;
    serviceCollections: Array<ServiceCollectionCatalogItem>;
};

export type TrailEntry = {
    id: string;
    occurredAt: string;
    source: string;
    kind: string;
    summary: string;
    severity: string;
    url: null | string;
    actor: null | string;
    objectType: null | string;
    objectId: null | string;
};

export type GetHealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type GetHealthLiveResponses = {
    200: unknown;
};

export type GetHealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type GetHealthReadyResponses = {
    200: unknown;
};

export type GetDemoAvailabilityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo';
};

export type GetDemoAvailabilityResponses = {
    200: DemoAvailability;
};

export type GetDemoAvailabilityResponse = GetDemoAvailabilityResponses[keyof GetDemoAvailabilityResponses];

export type ListCasesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/cases';
};

export type ListCasesErrors = {
    401: ProblemDetails;
};

export type ListCasesError = ListCasesErrors[keyof ListCasesErrors];

export type ListCasesResponses = {
    200: RecentCases;
};

export type ListCasesResponse = ListCasesResponses[keyof ListCasesResponses];

export type CreateCaseData = {
    body: CreateCaseRequest;
    headers?: {
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/cases';
};

export type CreateCaseErrors = {
    400: ProblemDetails;
    401: ProblemDetails;
    403: ProblemDetails;
    409: ProblemDetails;
};

export type CreateCaseError = CreateCaseErrors[keyof CreateCaseErrors];

export type CreateCaseResponses = {
    201: CreateCaseResponse;
};

export type CreateCaseResponse2 = CreateCaseResponses[keyof CreateCaseResponses];

export type ListCaseInputsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/cases/{id}/inputs';
};

export type ListCaseInputsErrors = {
    401: ProblemDetails;
    403: ProblemDetails;
    404: ProblemDetails;
};

export type ListCaseInputsError = ListCaseInputsErrors[keyof ListCaseInputsErrors];

export type ListCaseInputsResponses = {
    200: PageOfCaseInput;
};

export type ListCaseInputsResponse = ListCaseInputsResponses[keyof ListCaseInputsResponses];

export type ResetDemoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo/reset';
};

export type ResetDemoResponses = {
    200: DemoReset;
};

export type ResetDemoResponse = ResetDemoResponses[keyof ResetDemoResponses];

export type GetOperationsCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/catalog';
};

export type GetOperationsCatalogResponses = {
    200: OperationsCatalog;
};

export type GetOperationsCatalogResponse = GetOperationsCatalogResponses[keyof GetOperationsCatalogResponses];

export type GetCaseFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cases/{id}';
};

export type GetCaseFileErrors = {
    401: unknown;
    403: unknown;
    404: unknown;
};

export type GetCaseFileResponses = {
    200: CaseFile;
    202: CasePending;
};

export type GetCaseFileResponse = GetCaseFileResponses[keyof GetCaseFileResponses];

export type GetCaseStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cases/{id}/status';
};

export type GetCaseStatusErrors = {
    401: unknown;
    403: unknown;
    404: unknown;
};

export type GetCaseStatusResponses = {
    200: CaseStatus;
};

export type GetCaseStatusResponse = GetCaseStatusResponses[keyof GetCaseStatusResponses];

export type GetCaseTrailData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/cases/{id}/trail';
};

export type GetCaseTrailErrors = {
    401: unknown;
    403: unknown;
    404: unknown;
};

export type GetCaseTrailResponses = {
    200: PageOfTrailEntry;
};

export type GetCaseTrailResponse = GetCaseTrailResponses[keyof GetCaseTrailResponses];

export type GetCaseCrumbsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/cases/{id}/crumbs';
};

export type GetCaseCrumbsErrors = {
    401: unknown;
    403: unknown;
    404: unknown;
};

export type GetCaseCrumbsResponses = {
    200: PageOfCrumb;
};

export type GetCaseCrumbsResponse = GetCaseCrumbsResponses[keyof GetCaseCrumbsResponses];

export type AppendCaseCrumbsData = {
    body: AppendCrumbsRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cases/{id}/crumbs';
};

export type AppendCaseCrumbsErrors = {
    400: ProblemDetails;
    401: ProblemDetails;
    403: ProblemDetails;
    404: ProblemDetails;
    409: ProblemDetails;
};

export type AppendCaseCrumbsError = AppendCaseCrumbsErrors[keyof AppendCaseCrumbsErrors];

export type AppendCaseCrumbsResponses = {
    200: AppendCrumbsResponse;
};

export type AppendCaseCrumbsResponse = AppendCaseCrumbsResponses[keyof AppendCaseCrumbsResponses];

export type GetRecentPagerDutyIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        since?: string;
        until?: string;
    };
    url: '/api/pagerduty/incidents';
};

export type GetRecentPagerDutyIncidentsErrors = {
    400: ProblemDetails;
    502: ProblemDetails;
    503: ProblemDetails;
};

export type GetRecentPagerDutyIncidentsError = GetRecentPagerDutyIncidentsErrors[keyof GetRecentPagerDutyIncidentsErrors];

export type GetRecentPagerDutyIncidentsResponses = {
    200: RecentPagerDutyIncidents;
};

export type GetRecentPagerDutyIncidentsResponse = GetRecentPagerDutyIncidentsResponses[keyof GetRecentPagerDutyIncidentsResponses];

export type TriggerPagerDutyIncidentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pagerduty/incidents/{id}/trigger';
};

export type TriggerPagerDutyIncidentErrors = {
    404: ProblemDetails;
    409: ProblemDetails;
    502: ProblemDetails;
    503: ProblemDetails;
};

export type TriggerPagerDutyIncidentError = TriggerPagerDutyIncidentErrors[keyof TriggerPagerDutyIncidentErrors];

export type TriggerPagerDutyIncidentResponses = {
    202: CaseTriggerResult;
};

export type TriggerPagerDutyIncidentResponse = TriggerPagerDutyIncidentResponses[keyof TriggerPagerDutyIncidentResponses];

export type RebuildCaseFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cases/{id}/rebuild';
};

export type RebuildCaseFileErrors = {
    401: ProblemDetails;
    403: ProblemDetails;
    404: ProblemDetails;
    409: ProblemDetails;
};

export type RebuildCaseFileError = RebuildCaseFileErrors[keyof RebuildCaseFileErrors];

export type RebuildCaseFileResponses = {
    202: RebuildCaseFileResponse;
};

export type RebuildCaseFileResponse2 = RebuildCaseFileResponses[keyof RebuildCaseFileResponses];

export type RefreshCaseSourcesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cases/{id}/refresh-sources';
};

export type RefreshCaseSourcesErrors = {
    401: ProblemDetails;
    403: ProblemDetails;
    404: ProblemDetails;
    409: ProblemDetails;
};

export type RefreshCaseSourcesError = RefreshCaseSourcesErrors[keyof RefreshCaseSourcesErrors];

export type RefreshCaseSourcesResponses = {
    202: RefreshCaseSourcesResponse;
};

export type RefreshCaseSourcesResponse2 = RefreshCaseSourcesResponses[keyof RefreshCaseSourcesResponses];

export type CloseCaseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cases/{id}/close';
};

export type CloseCaseErrors = {
    401: ProblemDetails;
    403: ProblemDetails;
    404: ProblemDetails;
    409: ProblemDetails;
};

export type CloseCaseError = CloseCaseErrors[keyof CloseCaseErrors];

export type CloseCaseResponses = {
    204: void;
};

export type CloseCaseResponse = CloseCaseResponses[keyof CloseCaseResponses];
